import test from "node:test";
import assert from "node:assert/strict";
import { catalogApi, CatalogApiError, csrfToken } from "../lib/catalog-api.js";

test("CSRF cookie parsing is exact and fail closed", () => { assert.equal(csrfToken("other=x; pcx_csrf=token%201"), "token 1"); assert.equal(csrfToken("pcx_csrf=%E0%A4%A"), null); assert.equal(csrfToken("pcx_csrfish=no"), null); });
test("catalog writes send credentials and double-submit CSRF without client-owned status", async () => { const priorDocument = global.document, priorFetch = global.fetch; global.document = { cookie: "pcx_csrf=secure" }; let call; global.fetch = async (...args) => { call = args; return { ok: true, status: 201, async json() { return { data: { id: "server-id", status: "ACTIVE" } }; } }; }; try { const result = await catalogApi.createBrand({ name: "PCX", slug: "pcx" }); assert.equal(result.data.id, "server-id"); assert.equal(call[0], "/api/v1/admin/brands"); assert.equal(call[1].credentials, "include"); assert.equal(call[1].headers["x-csrf-token"], "secure"); assert.equal(JSON.parse(call[1].body).status, undefined); } finally { global.document = priorDocument; global.fetch = priorFetch; } });
test("catalog API surfaces stable server errors and refuses writes without CSRF", async () => { const priorDocument = global.document, priorFetch = global.fetch; global.document = { cookie: "" }; try { await assert.rejects(() => catalogApi.archive("brands", "b1"), (e) => e instanceof CatalogApiError && e.code === "CSRF_MISSING"); global.document = { cookie: "pcx_csrf=x" }; global.fetch = async () => ({ ok: false, status: 403, async json() { return { error: { code: "FORBIDDEN", message: "Operation is not allowed" } }; } }); await assert.rejects(() => catalogApi.createBrand({ name: "x" }), (e) => e.code === "FORBIDDEN" && e.status === 403); } finally { global.document = priorDocument; global.fetch = priorFetch; } });
test("model specification adapter addresses encoded model and definition IDs", async () => { const priorDocument = global.document, priorFetch = global.fetch; global.document = { cookie: "pcx_csrf=x" }; let path; global.fetch = async (url) => { path = url; return { ok: true, status: 200, async json() { return { data: { value: true } }; } }; }; try { await catalogApi.setModelValue("model/one", "definition one", true); assert.equal(path, "/api/v1/admin/product-models/model%2Fone/specifications/definition%20one"); } finally { global.document = priorDocument; global.fetch = priorFetch; } });
test("catalog model list defaults to 50 and appends an encoded cursor when provided", async () => { const priorFetch = global.fetch; let path; global.fetch = async (url) => { path = url; return { ok: true, status: 200, async json() { return { data: [], meta: { nextCursor: null } }; } }; }; try { await catalogApi.models(); assert.equal(path, "/api/v1/product-models?limit=50"); await catalogApi.models({ cursor: "Ab C/d+" }); assert.equal(path, "/api/v1/product-models?limit=50&cursor=Ab%20C%2Fd%2B"); } finally { global.fetch = priorFetch; } });
