-- Media upload (local/NFS-backed, MEDIA_ROOT). The binary lives on disk (or a
-- later TrueNAS NFS mount pointed at by MEDIA_ROOT); this table stores only
-- metadata and links media to its owner entity. Public/private visibility
-- controls who may read the object. No user-controlled path or filename is ever
-- stored; `storage_key` is generated by the server.

CREATE TABLE IF NOT EXISTS media (
  id uuid PRIMARY KEY,
  storage_key text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL CHECK (size_bytes > 0),
  visibility text NOT NULL CHECK (visibility IN ('PUBLIC', 'PRIVATE')),
  purpose text NOT NULL,
  uploaded_by uuid REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS media_visibility_idx ON media(visibility, created_at DESC);

CREATE TABLE IF NOT EXISTS sell_request_media (
  id uuid PRIMARY KEY,
  sell_request_id uuid NOT NULL REFERENCES sell_requests(id) ON DELETE CASCADE,
  media_id uuid NOT NULL REFERENCES media(id) ON DELETE CASCADE,
  purpose text NOT NULL,
  UNIQUE(sell_request_id, media_id)
);

CREATE TABLE IF NOT EXISTS inspection_media (
  id uuid PRIMARY KEY,
  inspection_id uuid NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  media_id uuid NOT NULL REFERENCES media(id) ON DELETE CASCADE,
  purpose text NOT NULL,
  UNIQUE(inspection_id, media_id)
);

CREATE TABLE IF NOT EXISTS listing_media (
  id uuid PRIMARY KEY,
  listing_id uuid NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  media_id uuid NOT NULL REFERENCES media(id) ON DELETE CASCADE,
  purpose text NOT NULL,
  UNIQUE(listing_id, media_id)
);
