"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { catalogApi } from "../../lib/catalog-api";

const resources=[{key:"categories",label:"Categories"},{key:"brands",label:"Brands"},{key:"models",label:"Product models"},{key:"definitions",label:"Attributes"}];
const plural={categories:"categories",brands:"brands",models:"product-models",definitions:"attribute-definitions"};
function slug(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function Banner({notice,onClose}){if(!notice)return null;return <div className={`banner ${notice.kind}`} role={notice.kind==="error"?"alert":"status"}><span>{notice.message}</span><button type="button" onClick={onClose} aria-label="Dismiss message">×</button></div>;}
function Field({label,name,...props}){return <label><span>{label}</span><input name={name} {...props}/></label>;}

export default function CatalogWorkspace(){
 const [active,setActive]=useState("categories"),[data,setData]=useState({categories:[],brands:[],models:[],definitions:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(null),[categoryFilter,setCategoryFilter]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const[categories,brands,models,definitions]=await Promise.all([catalogApi.categories(),catalogApi.brands(),catalogApi.models(),catalogApi.definitions(categoryFilter)]);setData({categories:categories.data,brands:brands.data,models:models.data,definitions:definitions.data});setNotice(null);}catch(error){setNotice({kind:"error",message:error.status===401?"Sign in with an authorized admin account to manage the catalog.":error.message});}finally{setLoading(false);}},[categoryFilter]);
 useEffect(()=>{load();},[load]);
 const names=useMemo(()=>({category:Object.fromEntries(data.categories.map((r)=>[r.id,r.name])),brand:Object.fromEntries(data.brands.map((r)=>[r.id,r.name]))}),[data]);
 async function create(event){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{if(active==="categories")await catalogApi.createCategory({name:form.get("name"),slug:slug(form.get("name")),sortOrder:Number(form.get("sortOrder")||0)});if(active==="brands")await catalogApi.createBrand({name:form.get("name"),slug:slug(form.get("name"))});if(active==="models")await catalogApi.createModel({name:form.get("name"),slug:slug(form.get("name")),categoryId:form.get("categoryId"),brandId:form.get("brandId"),modelCode:form.get("modelCode")||null,searchAliases:form.get("aliases").split(",").map((v)=>v.trim()).filter(Boolean)});if(active==="definitions")await catalogApi.createDefinition({categoryId:form.get("categoryId"),key:form.get("key"),label:form.get("label"),dataType:form.get("dataType"),unit:form.get("unit")||null,filterable:form.get("filterable")==="on",required:form.get("required")==="on",sortOrder:Number(form.get("sortOrder")||0)});event.currentTarget.reset();setNotice({kind:"success",message:"Catalog record saved."});await load();}catch(error){setNotice({kind:"error",message:error.message});}finally{setBusy(false);}}
 async function archive(record){if(!window.confirm(`Archive ${record.name??record.label}? Historical references will be preserved.`))return;setBusy(true);try{await catalogApi.archive(plural[active],record.id);setNotice({kind:"success",message:"Record archived. Historical references remain intact."});await load();}catch(error){setNotice({kind:"error",message:error.message});}finally{setBusy(false);}}
 async function edit(record){const current=record.label??record.name,next=window.prompt(`Update ${active==="definitions"?"attribute label":"name"}`,current);if(next==null||!next.trim()||next.trim()===current)return;setBusy(true);try{await catalogApi.update(plural[active],record.id,active==="definitions"?{label:next.trim()}:{name:next.trim()});setNotice({kind:"success",message:"Record updated."});await load();}catch(error){setNotice({kind:"error",message:error.message});}finally{setBusy(false);}}
 const rows=data[active];
 return <main><aside><a className="brand" href="/catalog" aria-label="PCX Admin home"><b>PCX</b><small>CONTROL ROOM</small></a><nav aria-label="Primary"><a className="selected" href="/catalog">Catalog</a><span>Product models</span><span>Inventory</span><span>Verification</span><span>Orders</span><span>Audit logs</span></nav><div className="secure">Server-authorized<br/><strong>Privileged workspace</strong></div></aside>
 <section className="content"><header><div><p className="eyebrow">OPERATIONS / CATALOG</p><h1>Catalog workspace</h1><p>Manage generic product identity and category-specific attributes. Physical serials, cost and health never belong here.</p></div><button className="refresh" type="button" onClick={load} disabled={loading}>↻ Refresh</button></header><Banner notice={notice} onClose={()=>setNotice(null)}/>
 <div className="tabs" role="tablist" aria-label="Catalog resources">{resources.map((r)=><button key={r.key} role="tab" aria-selected={active===r.key} onClick={()=>setActive(r.key)}>{r.label}<span>{data[r.key].length}</span></button>)}</div>
 <div className="grid"><section className="panel"><div className="panelTitle"><div><p className="eyebrow">ACTIVE RECORDS</p><h2>{resources.find((r)=>r.key===active).label}</h2></div>{active==="definitions"&&<label className="filter"><span>Category</span><select value={categoryFilter} onChange={(e)=>setCategoryFilter(e.target.value)}><option value="">All categories</option>{data.categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</div>
 {loading?<p className="state" role="status">Loading catalog…</p>:rows.length===0?<p className="state">No active records found.</p>:<div className="tableWrap"><table><thead><tr><th>Name</th><th>Context</th><th>Status</th><th><span className="sr">Actions</span></th></tr></thead><tbody>{rows.map((r)=><tr key={r.id}><td><strong>{r.name??r.label}</strong><small>{r.slug??r.key}</small></td><td>{active==="models"?`${names.brand[r.brandId]??"Unknown brand"} · ${names.category[r.categoryId]??"Unknown category"}`:active==="definitions"?`${names.category[r.categoryId]??"Unknown category"} · ${r.dataType}${r.unit?` · ${r.unit}`:""}`:r.parentId?"Nested category":"Catalog root"}</td><td><span className="pill">Active</span></td><td><div className="actions"><button type="button" disabled={busy} onClick={()=>edit(r)}>Edit</button><button className="danger" type="button" disabled={busy} onClick={()=>archive(r)}>Archive</button></div></td></tr>)}</tbody></table></div>}</section>
 <section className="panel formPanel"><p className="eyebrow">CREATE RECORD</p><h2>New {resources.find((r)=>r.key===active).label.toLowerCase().replace(/s$/," ")}</h2><p>IDs, lifecycle status and audit actor are assigned by the server.</p><form onSubmit={create}>{active==="categories"&&<><Field label="Category name" name="name" required maxLength="120"/><Field label="Sort order" name="sortOrder" type="number" min="0" defaultValue="0"/></>}{active==="brands"&&<Field label="Brand name" name="name" required maxLength="120"/>}{active==="models"&&<><Field label="Model name" name="name" required maxLength="160"/><label><span>Category</span><select name="categoryId" required><option value="">Select category</option>{data.categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Brand</span><select name="brandId" required><option value="">Select brand</option>{data.brands.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Field label="Model code (optional)" name="modelCode"/><Field label="Search aliases (comma separated)" name="aliases"/></>}{active==="definitions"&&<><label><span>Category</span><select name="categoryId" required><option value="">Select category</option>{data.categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Canonical key" name="key" pattern="[a-z][a-z0-9_]*" placeholder="memory_gb" required/><Field label="Display label" name="label" required/><label><span>Data type</span><select name="dataType" required><option>TEXT</option><option>NUMBER</option><option>BOOLEAN</option><option>JSON</option></select></label><Field label="Unit (optional)" name="unit"/><Field label="Sort order" name="sortOrder" type="number" min="0" defaultValue="0"/><label className="check"><input type="checkbox" name="filterable"/><span>Available as a catalog filter</span></label><label className="check"><input type="checkbox" name="required"/><span>Required for models in this category</span></label></>}<button className="primary" disabled={busy||loading}>{busy?"Saving…":"Save record"}</button></form></section></div></section></main>;
}
