"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { catalogApi } from "../../../../../lib/catalog-api";

function display(value,type){if(value==null)return"";return type==="JSON"?JSON.stringify(value,null,2):String(value);}
function parse(value,type){if(type==="NUMBER"){const number=Number(value);if(!Number.isFinite(number))throw new Error("Enter a finite number.");return number;}if(type==="BOOLEAN")return value==="true";if(type==="JSON"){try{return JSON.parse(value);}catch{throw new Error("Enter a valid JSON object or array.");}}return value;}
function Input({definition,current}){if(definition.dataType==="BOOLEAN")return <select name="value" defaultValue={display(current,"BOOLEAN")} required><option value="">Select value</option><option value="true">True</option><option value="false">False</option></select>;if(definition.dataType==="JSON")return <textarea name="value" defaultValue={display(current,"JSON")} placeholder='{"key":"value"}' required/>;return <input name="value" type={definition.dataType==="NUMBER"?"number":"text"} step={definition.dataType==="NUMBER"?"any":undefined} defaultValue={display(current,definition.dataType)} required/>;}

export default function ModelSpecifications({modelId}){const[model,setModel]=useState(null),[definitions,setDefinitions]=useState([]),[values,setValues]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(null),[notice,setNotice]=useState(null);
 const load=useCallback(async()=>{setLoading(true);try{const modelResult=await catalogApi.model(modelId);const[definitionResult,valueResult]=await Promise.all([catalogApi.definitions(modelResult.data.categoryId),catalogApi.modelValues(modelId)]);setModel(modelResult.data);setDefinitions(definitionResult.data);setValues(valueResult.data);setNotice(null);}catch(error){setNotice({kind:"error",message:error.status===401?"Sign in with an authorized admin account.":error.message});}finally{setLoading(false);}},[modelId]);useEffect(()=>{load();},[load]);
 const byDefinition=useMemo(()=>Object.fromEntries(values.map((item)=>[item.specificationDefinitionId,item])),[values]);
 async function save(event,definition){event.preventDefault();setSaving(definition.id);try{const input=new FormData(event.currentTarget).get("value"),value=parse(input,definition.dataType);const result=await catalogApi.setModelValue(modelId,definition.id,value);setValues((current)=>[...current.filter((item)=>item.specificationDefinitionId!==definition.id),{...result.data,label:definition.label,key:definition.key,unit:definition.unit}]);setNotice({kind:"success",message:`${definition.label} saved.`});}catch(error){setNotice({kind:"error",message:error.message});}finally{setSaving(null);}}
 return <main className="detailPage"><section className="detailContent"><a className="back" href="/catalog">← Catalog workspace</a><header><div><p className="eyebrow">PRODUCT MODEL / SPECIFICATIONS</p><h1>{model?.name??"Model specifications"}</h1><p>Assign category-approved typed values. The server rejects mismatched categories and data types.</p></div><button className="refresh" onClick={load} disabled={loading}>↻ Refresh</button></header>{notice&&<div className={`banner ${notice.kind}`} role={notice.kind==="error"?"alert":"status"}>{notice.message}<button onClick={()=>setNotice(null)} aria-label="Dismiss message">×</button></div>}{loading?<div className="panel state" role="status">Loading model attributes…</div>:definitions.length===0?<div className="panel state">No active attribute definitions exist for this category.</div>:<section className="specGrid" aria-label="Model attributes">{definitions.map((definition)=>{const current=byDefinition[definition.id];return <form className="panel specCard" key={definition.id} onSubmit={(event)=>save(event,definition)}><div><div className="specHeading"><h2>{definition.label}</h2>{definition.required&&<span className="required">Required</span>}</div><code>{definition.key}</code><p>{definition.dataType}{definition.unit?` · ${definition.unit}`:""}{definition.filterable?" · Storefront filter":""}</p></div><label><span>Value{definition.unit?` (${definition.unit})`:""}</span><Input definition={definition} current={current?.value}/></label><div className="specFooter"><small>{current?`Updated ${new Date(current.updatedAt).toLocaleString()}`:"Not set"}</small><button className="primary" disabled={saving===definition.id}>{saving===definition.id?"Saving…":current?"Update value":"Set value"}</button></div></form>;})}</section>}</section></main>;
}
