import test from "node:test";
import assert from "node:assert/strict";
import { createCatalogSpecCommandService, CatalogSpecCommandError } from "../src/modules/catalog/catalog-spec-command-service.mjs";

const admin={userId:"11111111-1111-4111-8111-111111111111",roles:["ADMIN"],status:"ACTIVE"};
function setup(identity=admin){let definition=null,value=null;const repository={async createDefinition(v){definition=v;return v;},async findDefinition(){return definition;},async findProductModel(){return{id:"model",categoryId:"category",status:"ACTIVE"};},async listDefinitions(){return definition?[definition]:[];},async updateDefinition(){return true;},async archiveDefinition(){return true;},async upsertValue(v){value=v;return v;},async upsertValues(records){records.forEach((r)=>{value=r;});return records;}};let n=0;const service=createCatalogSpecCommandService({authService:{async authenticateAccess(){return identity;}},repository,id:()=>`id-${++n}`,clock:()=>new Date("2026-08-16T00:00:00Z")});return{service,repository,get value(){return value;}};}
test("spec admin owns identity/lifecycle and validates typed model values",async()=>{const state=setup();const definition=await state.service.createDefinition("access",{categoryId:"category",key:"ram_gb",label:"RAM",dataType:"NUMBER",unit:"GB",filterable:true,required:true,sortOrder:1});assert.equal(definition.id,"id-1");assert.equal(definition.status,"ACTIVE");const value=await state.service.upsertValue("access","model",definition.id,{value:16});assert.equal(value.value,16);await assert.rejects(()=>state.service.upsertValue("access","model",definition.id,{value:"16"}),(e)=>e instanceof CatalogSpecCommandError&&e.code==="invalid_input");});
test("spec admin denies non-admin and mass assignment",async()=>{await assert.rejects(()=>setup({userId:"u",roles:["CUSTOMER"],status:"ACTIVE"}).service.createDefinition("access",{}),(e)=>e.code==="forbidden");await assert.rejects(()=>setup().service.createDefinition("access",{id:"client"}),(e)=>e.code==="invalid_input");});
test("definition updates keep category, key, and type immutable",async()=>{const{service}=setup();const created=await service.createDefinition("a",{categoryId:"category",key:"color",label:"Color",dataType:"TEXT"});await assert.rejects(()=>service.updateDefinition("a",created.id,{dataType:"JSON"}),(e)=>e.code==="invalid_input");const updated=await service.updateDefinition("a",created.id,{label:"Finish"});assert.equal(updated.key,"color");assert.equal(updated.dataType,"TEXT");});
test("definition query is authorized and category-filtered",async()=>{let filters;const repository={async createDefinition(){},async findDefinition(){},async findProductModel(){},async listDefinitions(value){filters=value;return[{id:"d1"}];},async updateDefinition(){},async archiveDefinition(){},async upsertValue(){},async upsertValues(){}};const service=createCatalogSpecCommandService({authService:{async authenticateAccess(){return admin;}},repository});assert.deepEqual(await service.listDefinitions("access",{categoryId:"category"}),{data:[{id:"d1"}]});assert.deepEqual(filters,{categoryId:"category"});await assert.rejects(()=>service.listDefinitions("access",{status:"ARCHIVED"}),(e)=>e.code==="invalid_input");});
test("model value query requires an active model and catalog permission",async()=>{const repository={async createDefinition(){},async findDefinition(){},async findProductModel(id){return id==="model"?{id}:null;},async listDefinitions(){return[];},async listValues(){return[{id:"v1",value:16}];},async updateDefinition(){},async archiveDefinition(){},async upsertValue(){},async upsertValues(){}};const service=createCatalogSpecCommandService({authService:{async authenticateAccess(){return admin;}},repository});assert.deepEqual(await service.listValues("access","model"),{data:[{id:"v1",value:16}]});await assert.rejects(()=>service.listValues("access","missing"),(e)=>e.code==="not_found");});
test("bulk upsertValues enforces required completeness atomically",async()=>{const state=setup();const required=await state.service.createDefinition("access",{categoryId:"category",key:"ram_gb",label:"RAM",dataType:"NUMBER",required:true});await assert.rejects(()=>state.service.upsertValues("access","model",{values:[]}),(e)=>e instanceof CatalogSpecCommandError&&e.code==="invalid_input");const saved=await state.service.upsertValues("access","model",{values:[{definitionId:required.id,value:32}]});assert.equal(saved[0].value,32);await assert.rejects(()=>state.service.upsertValues("access","model",{values:[{definitionId:"missing",value:1}]}),(e)=>e.code==="not_found");});
