import test from "node:test";
import assert from "node:assert/strict";
import { createRequestHandler } from "../src/server.mjs";
const origin="https://admin.pcx.test";
function service(overrides={}){return{async listDefinitions(){return{data:[]};},async createDefinition(){return{id:"d1"};},async updateDefinition(){return{id:"d1"};},async archiveDefinition(){},async upsertValue(){return{id:"v1"};},...overrides};}
async function invoke(path,{method="POST",body={},headers={},catalogSpecCommandService=service()}={}){const out={};const response={setHeader(){},writeHead(s){out.status=s;return response;},end(v){out.body=v?JSON.parse(v):undefined;return response;}};const payload=JSON.stringify(body),request={url:path,method,headers:{origin,"content-type":"application/json",cookie:"pcx_access=a; pcx_csrf=c","x-csrf-token":"c",...headers},async *[Symbol.asyncIterator](){yield Buffer.from(payload);}};await createRequestHandler({catalogSpecCommandService,allowedOrigins:new Set([origin])})(request,response);return out;}
test("spec definition and model-value routes call protected commands",async()=>{let called;let r=await invoke("/api/v1/admin/attribute-definitions",{body:{key:"ram"},catalogSpecCommandService:service({async createDefinition(...a){called=a;return{id:"d"};}})});assert.equal(r.status,201);assert.equal(called[0],"a");r=await invoke("/api/v1/admin/product-models/m1/specifications/d1",{method:"PUT",body:{value:8}});assert.equal(r.status,200);});
test("spec routes fail closed for CSRF, origin, method, and missing service",async()=>{assert.equal((await invoke("/api/v1/admin/attribute-definitions",{headers:{"x-csrf-token":"bad"}})).status,403);assert.equal((await invoke("/api/v1/admin/attribute-definitions",{headers:{origin:"https://evil.test"}})).status,403);assert.equal((await invoke("/api/v1/admin/attribute-definitions/d1",{method:"GET"})).status,405);assert.equal((await invoke("/api/v1/admin/attribute-definitions",{catalogSpecCommandService:null})).status,503);});
test("spec definition query authenticates without requiring write CSRF",async()=>{let call;const response=await invoke("/api/v1/admin/attribute-definitions?categoryId=c1",{method:"GET",headers:{"x-csrf-token":""},catalogSpecCommandService:service({async listDefinitions(...args){call=args;return{data:[{id:"d1"}]};}})});assert.equal(response.status,200);assert.deepEqual(call.slice(0,2),["a",{categoryId:"c1"}]);});
