"use client";

import { useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { shipmentApi } from "../../../lib/shipment-api.js";
import ShipmentMediaModal from "./media-modal";

function Banner({ notice, onClose }) { if (!notice) return null; return <div className={`banner ${notice.kind}`} role={notice.kind === "error" ? "alert" : "status"}><span>{notice.message}</span><button type="button" onClick={onClose} aria-label="Dismiss message">×</button></div>; }
function Field({ label, name, defaultValue, ...props }) { return <label><span>{label}</span><input name={name} defaultValue={defaultValue} {...props} /></label>; }

async function run(action, setBusy, setNotice) {
  setBusy(true);
  setNotice(null);
  try {
    await action();
    setNotice({ kind: "success", message: "Action completed." });
  } catch (error) {
    setNotice({ kind: "error", message: error.message });
  } finally {
    setBusy(false);
  }
}

function ShipDialog({ shipment, busy, onClose, onConfirm }) {
  function submit(event) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const address = {
      recipientName: form.get("recipientName"),
      phone: form.get("phone"),
      line1: form.get("line1"),
      city: form.get("city"),
      postalCode: form.get("postalCode"),
      country: form.get("country") || "BD"
    };
    onConfirm(shipment.id, address);
  }

  return createPortal(
    <div className="modalOverlay" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
      <form className="modalDialog" role="dialog" aria-modal="true" aria-labelledby="ship-dialog-title" onSubmit={submit}>
        <button type="button" className="modalClose" aria-label="Close" onClick={onClose}>×</button>
        <h2 id="ship-dialog-title">Mark shipped</h2>
        <p>Shipment <strong>{shipment?.id ? `${shipment.id.slice(0, 8)}…` : ""}</strong>. The tracking id is generated by the courier on the server.</p>
        <label><span>Recipient name</span><input name="recipientName" required /></label>
        <label><span>Phone</span><input name="phone" required /></label>
        <label><span>Address line 1</span><input name="line1" required /></label>
        <label><span>City</span><input name="city" required /></label>
        <label><span>Postal code</span><input name="postalCode" /></label>
        <label><span>Country</span><input name="country" defaultValue="BD" /></label>
        <div className="modalActions">
          <button type="button" className="danger" onClick={onClose} disabled={busy}>Cancel</button>
          <button type="submit" className="primary" disabled={busy}>{busy ? "Shipping…" : "Mark shipped"}</button>
        </div>
      </form>
    </div>,
    document.body
  );
}

export default function ShipmentPage() {
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [shipments, setShipments] = useState([]);
  const [shipTarget, setShipTarget] = useState(null);
  const [mediaTarget, setMediaTarget] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const payload = await shipmentApi.list();
      setShipments(payload.data ?? []);
      setNotice(null);
    } catch (error) {
      setNotice({ kind: "error", message: error.status === 401 ? "Sign in to view shipments." : error.message });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  async function create(event) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    await run(() => shipmentApi.create({
      orderId: form.get("orderId"),
      courier: form.get("courier"),
      packageType: form.get("packageType") || null,
      weight: form.get("weight") ? Number(form.get("weight")) : null,
      codAmount: form.get("codAmount") ? Number(form.get("codAmount")) : null,
      shippingCharge: form.get("shippingCharge") ? Number(form.get("shippingCharge")) : null
    }), setBusy, setNotice);
    event.currentTarget.reset();
    await load();
  }

  async function ship(shipmentId, address) {
    await run(() => shipmentApi.ship(shipmentId, address), setBusy, setNotice);
    setShipTarget(null);
    await load();
  }

  async function deliver(shipmentId) {
    await run(() => shipmentApi.deliver(shipmentId), setBusy, setNotice);
    await load();
  }

  async function returnShipment(shipmentId) {
    await run(() => shipmentApi.return(shipmentId), setBusy, setNotice);
    await load();
  }

  return (
    <>
      <header>
        <div>
          <p className="eyebrow">OPERATIONS / SHIPMENT</p>
          <h1>Shipment</h1>
          <p>Track and act on each shipment row. Tracking id and lifecycle state are server-owned.</p>
        </div>
        <button className="refresh" type="button" onClick={load} disabled={loading}>↻ Refresh</button>
      </header>
      <Banner notice={notice} onClose={() => setNotice(null)} />
      <section className="panel">
        <div className="panelTitle">
          <div>
            <p className="eyebrow">SHIPMENTS</p>
            <h2>Recent shipments</h2>
          </div>
        </div>
        {loading ? <p className="state" role="status">Loading shipments…</p> : shipments.length === 0 ? <p className="state">No shipments yet.</p> : (
          <div className="tableWrap">
            <table>
              <thead><tr><th>Shipment</th><th>Order</th><th>Courier</th><th>Tracking</th><th>Status</th><th><span className="sr">Actions</span></th></tr></thead>
              <tbody>
                {shipments.map((s) => (
                  <tr key={s.id}>
                    <td><strong>{s.id.slice(0, 8)}…</strong></td>
                    <td>{s.orderId.slice(0, 8)}…</td>
                    <td>{s.courier}</td>
                    <td>{s.trackingId ?? "—"}</td>
                    <td><span className="pill">{s.status}</span></td>
                    <td>
                      <div className="actions">
                        {s.status === "DRAFT" && <button type="button" disabled={busy} onClick={() => setShipTarget(s)}>Mark shipped</button>}
                        {s.status === "SHIPPED" && <button type="button" disabled={busy} onClick={() => deliver(s.id)}>Mark delivered</button>}
                        {s.status === "SHIPPED" && <button type="button" disabled={busy} onClick={() => returnShipment(s.id)}>Return to origin</button>}
                        <button type="button" disabled={busy} onClick={() => setMediaTarget(s)}>Photos</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
      <section className="panel formPanel" style={{ marginTop: 18 }}>
        <p className="eyebrow">CREATE</p>
        <h2>New shipment</h2>
        <form onSubmit={create}>
          <Field label="Order ID" name="orderId" required />
          <Field label="Courier" name="courier" required />
          <Field label="Package type" name="packageType" required />
          <Field label="Weight" name="weight" type="number" min="0" step="any" required />
          <Field label="COD amount" name="codAmount" type="number" min="0" />
          <Field label="Shipping charge" name="shippingCharge" type="number" min="0" />
          <button className="primary" disabled={busy}>Create shipment</button>
        </form>
      </section>
      {shipTarget && (
        <ShipDialog
          shipment={shipTarget}
          busy={busy}
          onClose={() => setShipTarget(null)}
          onConfirm={ship}
        />
      )}
      {mediaTarget && <ShipmentMediaModal shipment={mediaTarget} onClose={() => setMediaTarget(null)} />}
    </>
  );
}
